_target_: demo_generation.demogen.DemoGen

source_name: agibot
task_name: mug_to_basket
source_id: 0
data_root: data/example_data/${task_name}/source_${source_id}
output_root: data/generated_data/${task_name}/source_${source_id}
preprocess_root: data/mani_data_preprocessed/${task_name}/source_${source_id}
confidence_thres: 30

task_n_object: 2
target_to_object: left

use_linear_interpolation: true
interpolate_step_size: 0.01
fixed_arms: 
  - left
target_cameras: 
  - head
  - hand_left
  - hand_right

use_manual_parsing_frames: true
parsing_frames:
  prepare: 30
  motion-1: 0
  skill-1: 90
  motion-2: 240
  skill-2: 270
  end: 480
load_cache: True
mask_names:
  object: mug
  target: box
  right_arm: right_arm
  left_arm: left_arm
  desktop: white desktop
  
generation:
  range_name: generate
  n_gen_per_source: 60  # 1 source demo --> how many target demos?, for single gpu
  check_multiply: 10
  n_grid_obj: 5
  n_grid_targ: 5
  render_video: false
  render_depth: true
  render_canny: false
  render_file: false
  mode: full_random
  disturbance: false
  adjust_speed: true
  
trans_range:
  generate:
    object: [[-0.2, -0.2, 0.0], [0.2, 0.2, 0.0]]
    target: [[-0.2, -0.2, 0.0], [0.2, 0.2, 0.0]] 

rot_range:
  generate:
    object: [-45, 15] # degree
    target: [-15, 15] # degree

relax_thresholds:
  # x_lower, x_upper, y_lower, y_upper, z_lower, z_upper
  object: [0.02, 0.02, 0.02, 0.02, 0, 0.02]
  target: [0.02, 0.02, 0.02, 0.02, 0, 0.02]
  desktop_z_thres: 0.02
  ee: [0.05, 0.05, 0.05]